### ISSUE TITLE
Frog Emoji String

### ISSUE THREAD

**Issue by codingbuffoon** [thcheetah777/frogWars#35]
I love the frog partials but they get a little distracting, maybe take some away? Also there should be a option for it in the settings.

**Comment by thcheetah777** [comment]
Hahahahahahahahaaaaa! 😂😂😂. I did that as a joke. Do you actually want the little froggies as an option?

**Comment by thcheetah777** [comment]
Maybe make it a secret setting?

**Comment by thcheetah777** [comment]
Ok. I'm gonna make a secret settings page.

**Comment by thcheetah777** [comment]
#37
